### ISSUE TITLE
Service Name/Description

### ISSUE THREAD

**Issue by PaulCoetser** [PeterKottas/DotNetCore.WindowsService#3] opened 2017-01-24 06:48 UTC
Hi Peter,

I'am using this library and I do struggle a little to setup this service.

I got it to install my service and start the service. The service name / description I provide gets ignored if I provide it like below.

public static void Main(string[] args)
{
ServiceRunner.Run(config =>
{
config.SetName("MY Service");
config.SetDescription("This service host a WebAPI");
}
}

if I run my install command as follows it does have the correct name / description but converted to all lower case (when viewed in local services - via control panel):
dotnet run action:install name:"MY CAPS Service" description:"UpperCase description of MY Service"

another question is when the service is already installed and started and I try to "install" it again I get a dotnet already inuse exception. If I stop the service manually before I run the install command it works.
my command I use to install:
dotnet run action:install

uninstall command:
dotnet run action:uninstall

Thank you

**Comment by PeterKottas** [comment] 2017-01-24 07:03
Hi Paul, thanks for the in-depth explanation. All seems valid points and hopefully easy to recreate. I'll look into it today after work and will let you know as soon as I know something.

**Comment by PaulCoetser** [comment] 2017-01-24 09:07
Thank you Peter!

Have you tried to host a WebAPI project with your service?  That is what I'am trying to do, but have more difficulties (Sorry).  

The WebAPI run nicely and retrieve my data from database when I use Kestrel to host my API.
When I run it through the service I keep on getting Ketrel "No Content" errors.  It might not really be a problem with your service, but maybe something with how I start my WebHostBuilder.

public void Start()
    {
      this.StartBase();
        File.AppendAllText(fileName, string.Format("Polling at {0}\n", DateTime.Now.ToString("o")));
    
      _host = new WebHostBuilder()
         .UseKestrel()
         .UseContentRoot(Directory.GetCurrentDirectory())
         .UseStartup<Startup>() //this Startup file is in my WebAPI Project that is setup with normal .netcore WebAPI project template
         .Build();

      // Make sure the windows service is stopped if the
      // ASP.NET Core stack stops for any reason
      _host
          .Services
          .GetRequiredService<IApplicationLifetime>()
          .ApplicationStopped
          .Register(() =>
          {
            if (stopRequestedByWindows == false)
            {
              Stop();
            }
          });

      Console.WriteLine("I started");
      File.AppendAllText(fileName, "Started\n");
      
      _host.Start();
    }

**Comment by PeterKottas** [comment] 2017-01-24 13:33
Ok no worries mate. I'll look into that as well. I think this lib might end up beeing useful for quite a few people so I am very happy to make it as good as possible. Actually (spoilers) next thing I want to add into this is something like http layer admin api. Where you could setup your own actions and call them from web ideally with authentication. So basically you could retrieve logs/start/stop/... and so on from web. In order to achieve something as fancy I will obviously need to solve the web host in this so I can almost guarantee this will be resolved quickly.

**Comment by PeterKottas** [comment] 2017-01-24 17:52
Ok so let's take it one at the time. 2 to be more precise.

1. First problem you got was not beeing able to set the name and description in code. This is (probably) by design. Basically parameters always override code. So if you want to set it in code, you'll need to call 
`public static void Main(string[] args)
{
ServiceRunner.Run(config =>
{
config.SetName("MY Service",true);
config.SetDescription("This service host a WebAPI",true);
}
}`
overriding default.

2. Second was a proper problem in code. It was actually my other lib: https://github.com/PeterKottas/DotNetCore.CmdArgParser just a bug in code which is now solved, just update your lib to version 1.0.9

3. Still need to research into this so keep tuned for updates ;)

**Comment by PaulCoetser** [comment] 2017-01-25 02:11
1)  It is working, I was missing the second parameter (Force = True)
2)  Thanks for this fix.  This works now.

to be able to have a custom name / description (as default) as well as parameters for the name / description I had to do the following in main().  

        var forceName = true;
        var forceDescription = true;

        foreach (var arg in args)
        {
          if (arg.StartsWith("name", StringComparison.CurrentCulture))
            forceName = false;
          if (arg.StartsWith("description", StringComparison.CurrentCulture))
            forceDescription = false;
        }

        name = "MY DEFAULT Service";
        config.SetName(name, forceName);
        config.SetDisplayName(name, forceName);
        config.SetDescription("This service host the MY DEFAULT Service WebAPI", forceDescription);

3)  I created a powershell script that make sure the service is stopped, before running the "install" command.  This works nicely and solved the issue of dotnet being inuse error.

Thank you for the quick response.  
Now to try and figure out how to get the API working correctly via the service.

**Comment by PeterKottas** [comment] 2017-01-25 16:07
Hi, cool, we managed to fix some things already :)
I made a new release that should make 2. much easier for you. Instead of the args black magic, you can now call:
`if(config.IsNameNullOrEmpty){
config.SetName(name, true);
}
else
{
config.SetName(name, false);
}`
or even simpler
'config.SetName(name, config.IsNameNullOrEmpty);'

Which will do the same thing essentially the same thing.

Basically calling it with false sets it only if it was not set by parameter. With these properties, you can come up with custom login around it.
That's release 1.0.10.
I made another one, 1.0.11 which if the service is installed already, it first stops it and only then reinstall. That should help with 2. 

Let me know if it works as you would expect. We'll get to the webhost then.

**Comment by PaulCoetser** [comment] 2017-01-26 00:00
Thank you Peter. Will check it on monday. On leave for couple of days.

**Comment by PeterKottas** [comment] 2017-01-26 10:50
Speak then, enjoy the time off :)

**Comment by PaulCoetser** [comment] 2017-01-30 06:11
Hi Peter, 

I have some difficulties to install the service.
I do a dotnet publish to an output folder. 
In that folder I do:
dotnet "myassembly.dll"  then all my calls work 100%
when I do
dotnet "myassembly.dll" action:install then I get the following error immediately (within a split second):

"Error 1053:  The service did not respond to the start or control request in a timely fashion" 

The service does appear within my local services, but when I try to start it, it just give the above mentioned error.

I then tried to get the latest code from GitHub, but those new Is*NullOrEmpty Extension methods is not available on the source tree. I want to do a few "file output's" to try and determine why the service does not want to start.  

The event viewer also has no valuable information in.
I also added the ServicesPipeTimeout to the registry but that does not make any difference.

Thank you

**Comment by ulkuniem** [comment] 2017-01-31 15:31
@PaulCoetser 
For the installation part there is possibility to publish standalone executable.
Check this as guide. 
[http://www.hanselman.com/blog/SelfcontainedNETCoreApplications.aspx]
(Basically remove remove "type="platform" from project.json and run dotnet publish -c release -r win10-x64)

For the Kestrel not finding files, the content root needs to be set other than current directory (as that might be win/system32 or something else that launches the service).
So for the WebApi host
`.UseContentRoot(Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName))`
Should do the trick.

**Comment by PaulCoetser** [comment] 2017-02-01 01:27
@ulkuniem 
Thank you for the advice on the publish.  I've done that and it works nicely now.  to install the service I run MyAssembly.exe action:install from my published folder.

After adding logging to my service I have discovered exactly what you mentioned above with regards to the Win\Systrem32 path.  I've also fixed it with the same statement what you mentioned above.  
Thank you.

**Comment by PeterKottas** [comment] 2017-02-10 19:22
Hello again, this issue is obviously interconnected with #5 I am pretty sure it should be fixed by now so just give 1.0.13 a shot and let me know. I will now have some more time to focus on this lib so can help if you have trouble.

**Closed** 2017-02-18 21:24 UTC
Labels: bug, enhancement
